accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView 

app_name = 'accounts'

urlpatterns = [
    path("profile/update", ProfileUpdateView.as_view(), name="update_profile"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profiles/<slug>", UserDetailView.as_view(), name="user_detail"),
    path("login/", LoginView.as_view(template_name='login.html'), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", Register.as_view(), name="register"),
]   

main/pycode/pycode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('messages/', include('message.urls', namespace='messages')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("posts/", PostsView.as_view(), name="posts"),
    path("posts/addpost", AddPostView.as_view(), name="addpost"),
    path("blogs/", BlogsView.as_view(), name="blogs"),
    path("mycontents/", MyPostsView.as_view(), name="content"),
    path("follow/", FollowView.as_view(), name="follow"),
    path("detail/", postdetail, name="postde")
]

pycode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('messages/', include('message.urls', namespace='messages')),
     path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IPAddressField
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Colors(models.Model):
	name = models.CharField('rang nomi', max_length=300)
	color = models.CharField('rangi', max_length=300)


class Jobs(models.Model):
    name = models.CharField('Kasbingiz', max_length=150)
    job_slug = models.SlugField('slug')

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'

    def __str__(self):
        return self.name
        

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile', null=True)
    slug = models.SlugField('userslug', max_length=200, unique=True)
    avatar = models.ImageField('avatar image', upload_to='user_avatars/', null=True, blank=True)
    bg_color = models.ForeignKey(Colors, on_delete=models.PROTECT, related_name='colors', blank=True, null=True)
    job = models.ForeignKey(Jobs, related_name=("jobs"), on_delete=models.PROTECT, null=True, blank=True)
    birth = models.DateField("Tug'ilgan Kuningiz", auto_now=False, auto_now_add=False, null=True, blank=True)
    place = models.CharField('place', max_length=250, null=True, blank=True)
    phone = models.CharField('Telefon raqam', max_length=25, null=True, blank=True)
    telegram = models.CharField('telegram', max_length=200, null=True, blank=True)    
    github = models.CharField('github', max_length=200, null=True, blank=True)    
    python = models.CharField('Python', max_length=2, blank=True)
    php = models.CharField('PHP', max_length=2, blank=True)
    js = models.CharField('JS', max_length=2, blank=True)
    java = models.CharField('Java', max_length=2, blank=True)
    c = models.CharField('C,C++,C#', max_length=2, blank=True)
    edu = RichTextField("Ta'lim", null=True, blank=True)
    edu_date = models.DateField("talim,Sanasi", null=True, blank=True)
    work = RichTextField('Ish', null=True, blank=True)
    work_date = models.DateField('Ish,sanasi', null=True, blank=True)
    bio = RichTextField('Bio', null=True, blank=True)
    note_title = models.CharField('note name', max_length=200, null=True, blank=True)
    note_body = models.TextField('note body', null=True, blank=True)

    def __str__(self):
    	return self.slug


    class Meta:
        verbose_name = 'User_profile'
        verbose_name_plural = 'User_profiles'

    def get_absolute_url(self):
        return reverse("accounts:user_detail", kwargs={"user_detail": self.slug})


# class UserPost(models.Model):
#     title = models.CharField('Po\'st nomi',max_length=400)
#     body = RichTextField()
#     image = ImageField('Po\'st rasmi',upload_to='user_post/')
#     tag = 













    

main/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.db.models.fields import IPAddressField
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
	name = models.CharField('category', max_length=100)
	slug = models.SlugField('slug', max_length=100)

	def __str__(self):
		return self.name


class Tag(models.Model):
	name = models.CharField('tag', max_length=100)
	slug = models.SlugField('slug', max_length=100)
	color = models.CharField('color', max_length=100)

	def __str__(self):
		return self.name


class Posts(models.Model):
	author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user_post', null=True)
	title = models.CharField('title',max_length=500)
	tag = models.ManyToManyField(Tag, related_name='posts')
	date = models.DateTimeField('date', auto_now_add=True)
	body = RichTextField('body')
	slug = models.SlugField('slug', max_length=30)

	def __str__(self):
		return self.title

class Blogs(models.Model):
	author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user_blog', null=True)
	title = models.CharField('title',max_length=500)
	category = models.ForeignKey(Category, related_name='blogs', on_delete=models.PROTECT, null=True)
	date = models.DateTimeField('date', auto_now_add=True)
	image = models.ImageField('image', upload_to='blogs/', blank=True)
	body = RichTextField('body')
	slug = models.SlugField('slug', max_length=30)

	def __str__(self):
		return self.title

main/pycode/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IPAddressField
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Colors(models.Model):
	name = models.CharField('rang nomi', max_length=300)
	color = models.CharField('rangi', max_length=300)


class Jobs(models.Model):
    name = models.CharField('Kasbingiz', max_length=150)
    job_slug = models.SlugField('slug')

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'

    def __str__(self):
        return self.name
        

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile', null=True)
    slug = models.SlugField('userslug', max_length=200)
    avatar = models.ImageField('avatar image', upload_to='user_avatars/', null=True, blank=True)
    bg_color = models.ForeignKey(Colors, on_delete=models.PROTECT, related_name='colors', blank=True, null=True)
    job = models.ForeignKey(Jobs, related_name=("jobs"), on_delete=models.PROTECT, null=True, blank=True)
    birth = models.DateField("Tug'ilgan Kuningiz", auto_now=False, auto_now_add=False, null=True, blank=True)
    place = models.CharField('place', max_length=250, null=True, blank=True)
    phone = models.CharField('Telefon raqam', max_length=25, null=True, blank=True)
    telegram = models.CharField('telegram', max_length=200, null=True, blank=True)    
    github = models.CharField('github', max_length=200, null=True, blank=True)    
    python = models.CharField('Python', max_length=2, blank=True)
    php = models.CharField('PHP', max_length=2, blank=True)
    js = models.CharField('JS', max_length=2, blank=True)
    java = models.CharField('Java', max_length=2, blank=True)
    c = models.CharField('C,C++,C#', max_length=2, blank=True)
    edu = RichTextField("Ta'lim", null=True, blank=True)
    edu_date = models.DateField("talim,Sanasi", null=True, blank=True)
    work = RichTextField('Ish', null=True, blank=True)
    work_date = models.DateField('Ish,sanasi', null=True, blank=True)
    bio = RichTextField('Bio', null=True, blank=True)
    note_title = models.CharField('note name', max_length=200, null=True, blank=True)
    note_body = models.TextField('note body', null=True, blank=True)

    def __str__(self):
    	return self.user.username


    class Meta:
        verbose_name = 'User_profile'
        verbose_name_plural = 'User_profiles'

    def get_absolute_url(self):
        return reverse("accounts:user_detail", kwargs={"user_detail": self.user.username})
    

accounts/forms.py
from typing import ClassVar
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from .models import *
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username","first_name",'last_name', "email", "password1", "password2"]
        widgets = {}

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['avatar','job','birth','place','phone',
        'telegram','github','python','php','js','java',
        'c','edu','edu_date','work','work_date','bio']


# class UpdateAvatar(forms.ModelForm):

#     class Meta:
#         model = UserProfile
#         fields = []

main/pycode/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from .models import *

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username","first_name",'last_name', "email", "password1", "password2"]
        widgets = {}

class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['job','birth','place','phone','python','php','js','java','c','edu','work','bio']

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic.base import View

import rstr

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.models import User
from .models import *
from main.models import Category, Posts
from .forms import *
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.

class ProfileView(LoginRequiredMixin, View):

	def get(self, request):
		return render(request, 'account.html')	


class UserDetailView(DetailView):
	model = UserProfile
	slug_field = 'slug'
	template_name = 'profile.html'


class ProfileUpdateView(LoginRequiredMixin,View):
	def get(self, request):
		form = UpdateProfileForm(instance=request.user.user_profile,)
		return render(request, 'settings.html',{'form':form})	

	def post(self, request):
		form = UpdateProfileForm(instance=request.user.user_profile,
								data=request.POST,
								files=request.FILES)
		if form.is_valid():
			form.save()
		else:
			form = UpdateProfileForm(instance=request.user.user_profile)

		return render(request, 'settings.html',{'form':form})
		


class Register(View):
	def get(self,request):
		form = RegisterForm(request.GET)
		context = {'form':form}
		return render(request,'signup.html', context)

	def post(self,request):
		form = RegisterForm(request.POST)
		if form.is_valid():
			print('@'*50)
			u = form.save()
			
			try:
				user = UserProfile.objects.create(user=u,slug=u.username)
				user.save()
				return redirect('/accounts/profile')
			except:
				user = None
				
			return redirect('/accounts/profile')
		else:
			print('#'*50)
			form = RegisterForm()


		context = {'form':form}
		return render(request,'signup.html', context)

main/pycode/accounts/views.py
from django.shortcuts import render

# Create your views here.

templates/addpost.html
{% extends 'wrapper.html' %}
{% load static %}


{% block content %}
	
<div class="app-wrapper">


<form action="", method="POST" class="p-5">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-6">
            <label for="">Post nomi</label>
            {{form.title}}
            <label for="">Post tegi (Ctrl bilan tanlang)</label>
            {{form.tag}}
        </div>
        <div class="col-lg-6">
            <label for="">Post matni</label>
            {{form.body}}
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary">Joylash</button>
</form>

<script>
    document.querySelector('#id_title').className='form-control mb-2'
    document.querySelector('#id_tag').className='form-control mb-2 w-50'
    document.querySelector('#id_body').className='form-control'
</script>
<script>
	if ( window.history.replaceState ) {
	 window.history.replaceState( null, null, window.location.href );
	}
</script>

</div>

{% endblock content %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
<head>
    <title>Portal - Bootstrap 5 Admin Dashboard Template For Developers</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="/static/assets/plugins/fontawesome/js/all.min.js"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="/static/assets/css/portal.css">

</head> 

<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="/static/assets/images/app-logo.svg" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-4"><a href="{% url 'main:home' %}"><span class="fa fa-code"></span> PyCode</a>  | Kirish</h2>
			        <div class="auth-form-container text-left">
						<form class="auth-form login-form" method="POST" action="">
							{% csrf_token %}         
							<div class="email mb-3">
								<label>Username</label>
								{{form.username}}
							</div><!--//form-group-->
							<div class="password mb-3">
								<label>Parol</label>
								{{form.password}}
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">Log In</button>
							</div>
						</form>
						<center><div class="text-muted mt-3 mb-3 small">-------yoki-------</div> 
							<button class="btn facebook"><span class="fab fa-facebook mr-3"></span>Facebook</button>
							<button class="btn google"><span class="fab fa-google mr-3"></span>Google</button></center>
						<div class="auth-option text-center pt-5">Hisobingiz yo'qmi? <a class="text-link" href="{% url 'accounts:register' %}" >Ro'yxatdan o'ting</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div>
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->
<script>
	document.querySelector('#id_username').className='form-control'
	document.querySelector('#id_password').className='form-control'
	if ( window.history.replaceState ) {
	 window.history.replaceState( null, null, window.location.href );
	}
</script>
<style>
	.facebook{
		background-color: rgb(63, 120, 226);
	}
	.google{
		background-color: rgb(172, 40, 40);
	}
</style>
<script>
	if ( window.history.replaceState ) {
	 window.history.replaceState( null, null, window.location.href );
	}
</script>
</body>
</html> 

templates/post-det.html
{% extends 'wrapper.html' %}
{% load static %}


{% block content %}
	<div class="container app-wrapper">
        <!-- detail header -->
        <div class="row justify-content-between align-items-center mt-5">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <h1>Post title wegver regrthgrtsh trhtyrjhy trhtrds</h1>
            </div>
            <div class="col-auto">
                <i>Sanasi: 12-yan, 2021</i>
                <hr>
                <a href="" class="btn btn-warning">Python</a>
                <a href="" class="btn btn-danger">Django</a>
                <a href="" class="btn btn-primary">beginer</a>
            </div>
            <div class="col-lg-3 col-md-3">
                <a href=""><div class="card p-3 mt-3">
                    <img src="/static/assets/images/users/user-1.jpg" class="avatar m-2" alt="user_avatar">
                    <h3>Abdulhamid</h3>
                    <p><a href="">followers: 46 </a>|<a href=""> following: 17</a></p>
                </div></a>
            </div>
        </div><hr>
        <!-- detail body -->
        <pre>
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("posts/", PostsView.as_view(), name="posts"),
    path("blogs/", BlogsView.as_view(), name="blogs"),
    path("mycontents/", MyPostsView.as_view(), name="content"),
    path("follow/", FollowView.as_view(), name="follow"),
    path("detail/", postdetail, name="postde")
]
        </pre>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis deleniti accusantium rem voluptatibus. Sed animi explicabo possimus voluptatibus maxime minima natus architecto, nesciunt, consequuntur, nobis saepe et ea nam impedit?</p>
    </div>
{% endblock content %}

templates/settings.html
{% extends 'wrapper.html' %}
{% load static %}

{% block content %}
	
	
    <div class="app-wrapper">
	    
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">			    
			    <h1 class="app-page-title">Profilni yangilash</h1>
			    <hr class="mb-4">
				<form class="settings-form" action="" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="row g-4 settings-section">
						<div class="col-12 col-md-4">
							<h3 class="section-title">Mening ma'lumotlarim</h3>
							<div class="section-intro">Ma'lumotlaringizni yozish o'zingizni ixtiyoringizda. Sizning ma'lumotlaringizdan foydalanmaymiz. <a href="help.html">Ko'proq</a></div>
						</div>
						<div class="col-12 col-md-8">
							<div class="app-card app-card-settings shadow-sm p-4">
								
						    <div class="app-card-body">
							    <div class="row">
									<div class="col-6">
										<div class="mb-3">
											{{form.avatar}}
										</div>
										<div class="mb-3">
										<label for="setting-input-1" class="form-label">Kasbingiz<span class="ml-2" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Umid qilamizki kasbingiz dasturchi"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-info-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z"/>
  <circle cx="8" cy="4.5" r="1"/>
</svg></span></label>
											{{form.job}}
										</div>
										<div class="mb-3">
											<label for="setting-input-2" class="form-label">Tug'ilgan kuningiz (kk.oo.yyyy)</label>
											{{form.birth}}
										</div>
										<div class="mb-3">
											<label for="setting-input-3" class="form-label">Manzilingiz</label>
											{{form.place}}
										</div>
									</div>

									<div class="col-6">
										<div class="mb-3">
											<label for="setting-input-3" class="form-label">Telefon no.</label>
											{{form.phone}}
										</div>
										<div class="mb-3">
											<label for="setting-input-2" class="form-label">Github (username)</label>
											{{form.github}}
										</div>
										<div class="mb-3">
											<label for="setting-input-2" class="form-label">Telegram (username)</label>
											{{form.telegram}}
										</div>
									</div>
								</div>
									
									
									
						    </div><!--//app-card-body-->
						    
						</div><!--//app-card-->
	                </div>
                </div><!--//row-->
                <hr class="my-4">
                <div class="row g-4 settings-section">
					<div class="col-12 col-md-4">
						<h3 class="section-title">Bilim darajasi (%)</h3>
		                <div class="section-intro">Qaysi dasturlash tilini qanchalik bilishingizni foizlarda yozing. <a href="help.html">Ko'proq</a></div>
	                </div>
	                <div class="col-12 col-md-8">
						<div class="app-card app-card-settings shadow-sm p-4">
								
							<div class="app-card-body">
								<div class="row">
									<div class="col-6">
										<label>Python</label>
										{{form.python}}
										<label>JS</label>
										{{form.js}}
										<label>PHP</label>
										{{form.php}}
										
									</div>
									<div class="col-6">
										<label>C++, C#, C</label>
										{{form.c}}
										<label>Java</label>
										{{form.java}}

									</div>
								</div>
						    </div><!--//app-card-body-->
						</div><!--//app-card-->
	                </div>
                </div><!--//row-->
                <hr class="my-4">
                <div class="row g-4 settings-section">
					<div class="col-12 col-md-4">
						<h3 class="section-title">Bio</h3>
		                <div class="section-intro">Bu sizning biografiyangiz. Bu sizni boshqa foydalanuvchilar yaqinroq tanishib olishi uchun.</div>
	                </div>
	                <div class="col-12 col-md-8">
						<div class="app-card app-card-settings shadow-sm p-4">						    
							<div class="app-card-body">
									
									{{form.bio}}
									<div class="mt-3">
									</div>
						    </div><!--//app-card-body-->						    
						</div><!--//app-card-->
	                </div>
                </div><!--//row-->
                <hr class="my-4">
                <div class="row g-4 settings-section">
	                <div class="col-12 col-md-4">
						<h3 class="section-title">Qo'shimcha ma'lumotlar</h3>
		                <div class="section-intro"></div>
	                </div>
	                <div class="col-12 col-md-8">
						<div class="app-card app-card-settings shadow-sm p-4">						    
							<div class="app-card-body">
								<div class="row">
									<div class="col-6">
										<h3 class="section-title">Ta'lim</h3>
										<label>Sana</label>
										{{form.edu_date}}
										<label>Tasurotlar</label>
										{{form.edu}}
									</div>
									<div class="col-6">
										<h3 class="section-title">Mehnat faoliyati</h3>
										<label>Sana</label>
										{{form.work_date}}
										<label>Tasurotlar</label>
										{{form.work}}
									</div>
								</div>
						    </div><!--//app-card-body-->						    
						</div><!--//app-card-->
	                </div>
					<div class="row fixed-bottom align-items-center justify-content-between">
						<div class="col-auto"></div>
						<div class="col-auto">
							<button type="submit" class="btn app-btn-primary m-3" ><span class="fa fa-file"></span> Saqlash</button>
						</div>
					</div>
                </div><!--//row-->
			</form>
			    <hr class="my-4">
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
	    
<script>
	document.querySelector('#id_avatar').className='form-control p-1'
	document.querySelector('#id_job').className='form-control'
	document.querySelector('#id_birth').className='form-control'
	document.querySelector('#id_place').className='form-control'
	document.querySelector('#id_phone').className='form-control'
	document.querySelector('#id_telegram').className='form-control'
	document.querySelector('#id_github').className='form-control'
	document.querySelector('#id_python').className='form-control w-50 mb-2'
	document.querySelector('#id_js').className='form-control w-50 mb-2'
	document.querySelector('#id_php').className='form-control w-50 mb-2'
	document.querySelector('#id_c').className='form-control w-50 mb-2'
	document.querySelector('#id_java').className='form-control w-50 mb-2'
	document.querySelector('#id_edu_date').className='form-control'
	document.querySelector('#id_work_date').className='form-control'
</script>
		{% endblock content %}